version: '3'

services:
  web_api:
    build: .
    command: /bin/bash -c "go run *.go"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:5.0
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "6381:6379"